esphome:
  name: inverter
  includes:
    - ABBAuroraStrings.cpp
    - ABBAuroraStrings.h
    - ABBAuroraEnums.h
    - ABBAurora.cpp
    - ABBAurora.h
    - InverterMonitor.h
  libraries:
    - "Wire"

esp32:
  board: esp32dev

api:
  encryption:
    key: !secret ha_key 
ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

i2c:
  sda: GPIO21
  scl: GPIO22
  scan: true
  id: bus_a

external_components:
  - source:
      type: git
      url: https://github.com/robertklep/esphome-custom-component
    components: [ custom, custom_component ]

sensor:
  - platform: bmp280_i2c
    i2c_id: bus_a
    temperature:
      name: "Temperatura garage"
    pressure:
      name: "Pressione Garage"
    update_interval: 60s

  - platform: aht10
    variant: AHT20
    i2c_id: bus_a
    humidity:
      name: "Umidità garage"
    temperature:
      name: "Temperatura Garage AHT20"
    update_interval: 60s

  - platform: custom
    lambda: |-
      auto monitor = InverterMonitor::get_instance();
      App.register_component(monitor);
      App.register_sensor(monitor->v_in_1);
      App.register_sensor(monitor->v_in_2);
      App.register_sensor(monitor->i_in_1);
      App.register_sensor(monitor->i_in_2);
      App.register_sensor(monitor->power_in_1);
      App.register_sensor(monitor->power_in_2);
      App.register_sensor(monitor->power_in_total);
      App.register_sensor(monitor->power_peak_today);
      App.register_sensor(monitor->power_peak_max);
      App.register_sensor(monitor->temperature_inverter);
      App.register_sensor(monitor->temperature_booster);
      App.register_sensor(monitor->cumulated_energy_today);
      App.register_sensor(monitor->cumulated_energy_week);
      App.register_sensor(monitor->cumulated_energy_month);
      App.register_sensor(monitor->cumulated_energy_year);
      App.register_sensor(monitor->cumulated_energy_total);
      App.register_sensor(monitor->grid_voltage);
      App.register_sensor(monitor->grid_current);
      App.register_sensor(monitor->grid_power);
      App.register_sensor(monitor->frequency);
      App.register_sensor(monitor->v_bulk);
      App.register_sensor(monitor->i_leak_dc_dc);
      App.register_sensor(monitor->i_leak_inverter);
      App.register_sensor(monitor->isolation_resistance);
      App.register_sensor(monitor->dc_dc_v_bulk);
      App.register_sensor(monitor->v_bulk_mid);
      App.register_sensor(monitor->grid_voltage_neutral);
      App.register_sensor(monitor->grid_voltage_neutral_phase);

      return {
        monitor->v_in_1,
        monitor->v_in_2,
        monitor->i_in_1,
        monitor->i_in_2,
        monitor->power_in_1,
        monitor->power_in_2,
        monitor->power_in_total,
        monitor->power_peak_today,
        monitor->power_peak_max,
        monitor->temperature_inverter,
        monitor->temperature_booster,
        monitor->cumulated_energy_today,
        monitor->cumulated_energy_week,
        monitor->cumulated_energy_month,
        monitor->cumulated_energy_year,
        monitor->cumulated_energy_total,
        monitor->grid_voltage,
        monitor->grid_current,
        monitor->grid_power,
        monitor->frequency,
        monitor->v_bulk,
        monitor->i_leak_dc_dc,
        monitor->i_leak_inverter,
        monitor->isolation_resistance,
        monitor->dc_dc_v_bulk,
        monitor->v_bulk_mid,
        monitor->grid_voltage_neutral,
        monitor->grid_voltage_neutral_phase,
      };

    sensors:
      - name: v_in_1
        id: v_in_1
        unit_of_measurement: V
        accuracy_decimals: 2
        icon: "mdi:lightning-bolt-outline"
        device_class: voltage
        state_class: measurement

      - name: v_in_2
        id: v_in_2
        unit_of_measurement: V
        accuracy_decimals: 2
        icon: "mdi:lightning-bolt-outline"
        device_class: voltage
        state_class: measurement

      - name: i_in_1
        id: i_in_1
        unit_of_measurement: A
        accuracy_decimals: 2
        icon: "mdi:current-ac"
        device_class: current
        state_class: measurement

      - name: i_in_2
        id: i_in_2
        unit_of_measurement: A
        accuracy_decimals: 2
        icon: "mdi:current-ac"
        device_class: current
        state_class: measurement

      - name: power_in_1
        id: power_in_1
        unit_of_measurement: W
        accuracy_decimals: 0
        icon: "mdi:solar-power"
        device_class: power
        state_class: measurement

      - name: power_in_2
        id: power_in_2
        unit_of_measurement: W
        accuracy_decimals: 0
        icon: "mdi:solar-power"
        device_class: power
        state_class: measurement

      - name: power_in_total
        id: power_in_total
        unit_of_measurement: W
        accuracy_decimals: 0
        icon: "mdi:solar-power"
        device_class: power
        state_class: measurement

      - name: power_peak_today
        id: power_peak_today
        unit_of_measurement: W
        accuracy_decimals: 0
        icon: "mdi:solar-power"
        device_class: power
        state_class: measurement

      - name: power_peak_max
        id: power_peak_max
        unit_of_measurement: W
        accuracy_decimals: 0
        icon: "mdi:solar-power"
        device_class: power
        state_class: measurement

      - name: inverter_temp
        id: inverter_temp
        unit_of_measurement: "°C"
        accuracy_decimals: 2
        icon: "mdi:thermometer"
        device_class: temperature
        state_class: measurement

      - name: booster_temp
        id: booster_temp
        unit_of_measurement: "°C"
        accuracy_decimals: 2
        icon: "mdi:thermometer"
        device_class: temperature
        state_class: measurement

      - name: cumulated_energy_today
        id: cumulated_energy_today
        unit_of_measurement: "Wh"
        accuracy_decimals: 0
        icon: "mdi:car-battery"
        device_class: energy
        state_class: total_increasing

      - name: cumulated_energy_week
        id: cumulated_energy_week
        unit_of_measurement: "Wh"
        accuracy_decimals: 0
        icon: "mdi:car-battery"
        device_class: energy
        state_class: total_increasing

      - name: cumulated_energy_month
        id: cumulated_energy_month
        unit_of_measurement: "Wh"
        accuracy_decimals: 0
        icon: "mdi:car-battery"
        device_class: energy
        state_class: total_increasing

      - name: cumulated_energy_year
        id: cumulated_energy_year
        unit_of_measurement: "Wh"
        accuracy_decimals: 0
        icon: "mdi:car-battery"
        device_class: energy
        state_class: total_increasing

      - name: cumulated_energy_total
        id: cumulated_energy_total
        unit_of_measurement: "Wh"
        accuracy_decimals: 0
        icon: "mdi:car-battery"
        device_class: energy
        state_class: total_increasing

      - name: Grid Voltage
        id: grid_voltage
        unit_of_measurement: V
        accuracy_decimals: 2
        icon: "mdi:flash"
        device_class: voltage
        state_class: measurement

      - name: Grid Current
        id: grid_current
        unit_of_measurement: A
        accuracy_decimals: 2
        icon: "mdi:current-ac"
        device_class: current
        state_class: measurement

      - name: Grid Power
        id: grid_power
        unit_of_measurement: W
        accuracy_decimals: 0
        icon: "mdi:flash"
        device_class: power
        state_class: measurement

      - name: Frequency
        id: frequency
        unit_of_measurement: Hz
        accuracy_decimals: 2
        icon: "mdi:sine-wave"
        device_class: frequency
        state_class: measurement

      - name: Bulk Voltage
        id: v_bulk
        unit_of_measurement: V
        accuracy_decimals: 2
        icon: "mdi:flash"
        device_class: voltage
        state_class: measurement

      - name: Isolation Resistance
        id: isolation_resistance
        unit_of_measurement: Ohm
        accuracy_decimals: 2
        icon: "mdi:resistor"
        device_class: voltage
        state_class: measurement

      - name: DC-DC V Bulk
        id: dc_dc_v_bulk
        unit_of_measurement: V
        accuracy_decimals: 2
        icon: "mdi:flash"
        device_class: voltage
        state_class: measurement

      - name: Bulk Mid Voltage
        id: v_bulk_mid
        unit_of_measurement: V
        accuracy_decimals: 2
        icon: "mdi:flash"
        device_class: voltage
        state_class: measurement

      - name: Grid Voltage Neutral
        id: grid_voltage_neutral
        unit_of_measurement: V
        accuracy_decimals: 2
        icon: "mdi:flash"
        device_class: voltage
        state_class: measurement

      - name: Grid Voltage Neutral Phase
        id: grid_voltage_neutral_phase
        unit_of_measurement: V
        accuracy_decimals: 2
        icon: "mdi:flash"
        device_class: voltage
        state_class: measurement

text_sensor:
  - platform: custom
    lambda: |-
      auto monitor = InverterMonitor::get_instance();
      App.register_text_sensor(monitor->connection_status);
      return { monitor->connection_status };
    text_sensors: 
      - name: connection_status
        icon: "mdi:connection"
